### ISSUE TITLE
Not working with x64 game

### ISSUE THREAD

**Issue by A-VORONKIN** [erfg12/memory.dll#1]
Can you make lib for x64 game?

**Comment by erfg12** [comment]
I don't know what you mean. You need to include this library file with Visual Studios. It works just fine with x64 code.

**Comment by erfg12** [comment]
If you have an issue with x64 programs...

Project Properties -> Build -> Platform Target -> x64

**Comment by Zaczero** [comment]
It's working for me fine.

**Comment by fabio24021990** [comment]
hi, what about AOB with IntPtr module (x64) for address start?

**Comment by erfg12** [comment]
You can now  open x64 addresses and read/write long addresses. It should be all set for 64 bit processes. Let me know if there are any issues.
