### ISSUE TITLE
Codecave didn't work 

### ISSUE THREAD

**Issue by ala-cpu** [erfg12/memory.dll#102]
1 - Codecave didn't work on Unreal engine games. 
2- can you show me an example to deallocation codecave on C#.

my code cave

        private void ToggleSwitch0_CheckedChanged(object sender, EventArgs e)
        {

            if (ProcOpen && ToggleSwitch0.Checked == true && ToggleSwitch0.Visible == true)
            {

                byte[] asm =
                    {
                      0x41,0xC7,0x07,0x00,0x40,0x9C,0x46,
                      0xF3,0x41,0x0F,0x10,0x07         
                    };

                Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5, asm.Length);
                cheat0.ForeColor = Color.OrangeRed;
                NumPad_0.ForeColor = Color.OrangeRed;
                Stream str = Properties.Resources.active;
                System.Media.SoundPlayer ASoundPlayer = new System.Media.SoundPlayer(str);
                ASoundPlayer.Play();

            }

            if (ProcOpen && ToggleSwitch0.Checked == false && ToggleSwitch0.Visible == true)
            {
                
                Dim.RE("AOM_Release_Final.exe+4203AD", "bytes", "F3 41 0F 10 07 F3 0F 11 44 24 34");
                off_cheatcolor();
                if (label_cls.Visible == false)
                {
                    Stream str3 = Properties.Resources.deactive;
                    System.Media.SoundPlayer DSoundPlayer = new System.Media.SoundPlayer(str3);
                    DSoundPlayer.Play();
                }

            }

        }

**Comment by ArmYof0n3** [comment]
For Dealloc CodeCave you need VirtualFreeEx function

```
        [DllImport("kernel32.dll", SetLastError = true, ExactSpelling = true)]
        static extern bool VirtualFreeEx(
            IntPtr hProcess,
            UIntPtr lpAddress,
            UIntPtr dwSize,
            uint dwFreeType
            );
```
CodeCave Example:

`long CodeCave = (long)Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5, asm.Length);`

Dealloc Example:

```
if(CodeCave > 0)
VirtualFreeEx(Dim.pHandle, (UIntPtr)CodeCave, (UIntPtr)0, 0x8000); //0x8000 MEM_RELESE
```

For more information you can read this : https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfreeex

**Comment by ArmYof0n3** [comment]
1. asm.lenght? - it is unnecessary and not correct !
     asm.lenght = 12...this is too little to create a codecave ...
     
     It must be so :  Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5);

     Also, if the script in the Cheat Engine requires 1 "nop", you must add +5 to the CodeCave function !
     1 + 5 = 6 etc. 
     
```
Example : 
 jmp newmem
  nop
return:
```
In this case it must be so: Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, **6**);
 
 If you have a problem creating an Unreal Engine CodeCave, read here -  - https://github.com/erfg12/memory.dll/issues/100 and - https://github.com/ArmYof0n3/memory.dll/commit/e9322b08f6548d02dcc8fa21ae59ffa6fcaa0049

2. For Dealloc CodeCave you need VirtualFreeEx function

Dealloc Example:

```
using System.Runtime.InteropServices;
        
[DllImport("kernel32.dll", SetLastError = true, ExactSpelling = true)]
        static extern bool VirtualFreeEx(
            IntPtr hProcess,
            UIntPtr lpAddress,
            UIntPtr dwSize,
            uint dwFreeType
            );

    long CodeCave = 0; 

    private void ToggleSwitch0_CheckedChanged(object sender, EventArgs e)
    {   
 
        if (ProcOpen && ToggleSwitch0.Checked == true && ToggleSwitch0.Visible == true)
        {

            byte[] asm =
                {
                  0x41,0xC7,0x07,0x00,0x40,0x9C,0x46,
                  0xF3,0x41,0x0F,0x10,0x07         
                };
            
            CodeCave = 0;
            CodeCave = (long)Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5);
            cheat0.ForeColor = Color.OrangeRed;
            NumPad_0.ForeColor = Color.OrangeRed;
            Stream str = Properties.Resources.active;
            System.Media.SoundPlayer ASoundPlayer = new System.Media.SoundPlayer(str);
            ASoundPlayer.Play();

        }


        if (ProcOpen && ToggleSwitch0.Checked == false && ToggleSwitch0.Visible == true)
        {
            
            Dim.RE("AOM_Release_Final.exe+4203AD", "bytes", "F3 41 0F 10 07 F3 0F 11 44 24 34");

            if (CodeCave > 0)
                    VirtualFreeEx(Dim.pHandle, (UIntPtr)CodeCave, (UIntPtr)0, 0x8000);
            
            off_cheatcolor();
            if (label_cls.Visible == false)
            {
                Stream str3 = Properties.Resources.deactive;
                System.Media.SoundPlayer DSoundPlayer = new System.Media.SoundPlayer(str3);
                DSoundPlayer.Play();
            }

        }

    }
```

For more information you can read this article : https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfreeex

If you have additional questions, please join the Discord chat channel: https://discord.gg/E3Hj7za

**Comment by ala-cpu** [comment]
> 1. asm.lenght? - it is unnecessary and not correct !
>    asm.lenght = 12...this is too little to create a codecave ...
>    It must be so :  Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5);
>    Also, if the script in the Cheat Engine requires 1 "nop", you must add +5 to the CodeCave function !
>    1 + 5 = 6 etc.
> 
> ```
> Example : 
>  jmp newmem
>   nop
> return:
> ```
> 
> In this case it must be so: Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, **6**);
> 
> If you have a problem creating an Unreal Engine CodeCave, read here - - #100 and - [ArmYof0n3@e9322b0](https://github.com/ArmYof0n3/memory.dll/commit/e9322b08f6548d02dcc8fa21ae59ffa6fcaa0049)
> 
> 1. For Dealloc CodeCave you need VirtualFreeEx function
> 
> Dealloc Example:
> 
> ```
> using System.Runtime.InteropServices;
>         
> [DllImport("kernel32.dll", SetLastError = true, ExactSpelling = true)]
>         static extern bool VirtualFreeEx(
>             IntPtr hProcess,
>             UIntPtr lpAddress,
>             UIntPtr dwSize,
>             uint dwFreeType
>             );
> 
>     long CodeCave = 0; 
> 
>     private void ToggleSwitch0_CheckedChanged(object sender, EventArgs e)
>     {   
>  
>         if (ProcOpen && ToggleSwitch0.Checked == true && ToggleSwitch0.Visible == true)
>         {
> 
>             byte[] asm =
>                 {
>                   0x41,0xC7,0x07,0x00,0x40,0x9C,0x46,
>                   0xF3,0x41,0x0F,0x10,0x07         
>                 };
>             
>             CodeCave = 0;
>             CodeCave = (long)Dim.CreateCodeCave("AOM_Release_Final.exe+4203AD", asm, 5);
>             cheat0.ForeColor = Color.OrangeRed;
>             NumPad_0.ForeColor = Color.OrangeRed;
>             Stream str = Properties.Resources.active;
>             System.Media.SoundPlayer ASoundPlayer = new System.Media.SoundPlayer(str);
>             ASoundPlayer.Play();
> 
>         }
> 
> 
>         if (ProcOpen && ToggleSwitch0.Checked == false && ToggleSwitch0.Visible == true)
>         {
>             
>             Dim.RE("AOM_Release_Final.exe+4203AD", "bytes", "F3 41 0F 10 07 F3 0F 11 44 24 34");
> 
>             if (CodeCave > 0)
>                     VirtualFreeEx(Dim.pHandle, (UIntPtr)CodeCave, (UIntPtr)0, 0x8000);
>             
>             off_cheatcolor();
>             if (label_cls.Visible == false)
>             {
>                 Stream str3 = Properties.Resources.deactive;
>                 System.Media.SoundPlayer DSoundPlayer = new System.Media.SoundPlayer(str3);
>                 DSoundPlayer.Play();
>             }
> 
>         }
> 
>     }
> ```
> 
> For more information you can read this article : https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualfreeex
> 
> If you have additional questions, please join the Discord chat channel: https://discord.gg/E3Hj7za



thanks man very helpful, especially deallocation code clean like water.
