### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Glatrix** [erfg12/memory.dll#103]
How would I move Unicode text from a pointer to a Label?

Sorry about the dumb question, I'm new to programming in
C#

**Comment by erfg12** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.label?view=net-5.0

Ask in our Discord channel if you have any further questions.

**Comment by Glatrix** [comment]
I don't see anything regarding Unicode.
Also my parents don't allow discord.
