### ISSUE TITLE
My code wont compile because of memory.dll

### ISSUE THREAD

**Issue by AmogusLand** [erfg12/memory.dll#115]
When i test the program it says this:
System.BadImageFormatException: 'Could not load file or assembly 'Memory, Version=1.2.21.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'
and when i build it it doesnt even start.
Ive tried to uninstall memory.dll_x64 and installed memory.dll_x86 but it still says the same.I was very thrilled to write my own memory thingy and now its not compiling.
![Annotation 2021-05-17 132448](https://user-images.githubusercontent.com/84322544/118481010-4da73f00-b713-11eb-9c6b-0a401fce7832.png)

**Comment by rxversedcode** [comment]
same

**Comment by Vincent11276** [comment]
Here's a solution I've tried that works at least for me.

https://stackoverflow.com/questions/67609029/wierd-errors-on-my-visual-studio-when-working-with-memory-dll-or-just-doing-anyt

**Comment by riya69** [comment]
I just decided to ditch the DLL, put the source into my project and it decided to work.
