### ISSUE TITLE
No generic read/write with defined length?

### ISSUE THREAD

**Issue by LeonBlade** [erfg12/memory.dll#12]
I was surprised string read/write doesn't have any specified length, but even just a generic read/write would work fine.  Any chance of adding something like this?

**Comment by erfg12** [comment]
Ok, I added length to readString as an optional value.

readString (string code, string file = "", int length = 32)

[image: New Age Software, LLC] <http://newage.software/>

Jacob Fliss / Software Programmer
jake@newage.software

New Age Software, LLC
(239) 307-0776 | Ext 500
http://newage.software

[image: Twitter]  <https://htmlsig.com/t/0000001BWJTT4> [image: Facebook]
<https://htmlsig.com/t/0000001BX7VE4> [image: Google +]
<https://htmlsig.com/t/0000001BVC6AJ> [image: Skype]
<https://htmlsig.com/t/0000001BVQW9G> [image: Youtube]
<https://htmlsig.com/t/0000001BSCGW0> [image: Github]
<https://htmlsig.com/t/0000001BSKJAA>
