### ISSUE TITLE
m.OpenProcess(PID) Crash

### ISSUE THREAD

**Issue by CanadianJeff** [erfg12/memory.dll#123]
So my setup is

Visual Studio 2022 Preview (Version 17.0.0 Preview 4.1)
Windows 10 64Bit Desktop PC
.Net Windows Form App New Project

I downloaded from the release page `Build 2021-09-13T23:40:30.0000000Z` both the x86 and x64 NuGet files created my trainer from https://github.com/0xInstintN0P/L4D2_AutoBunnyHop/blob/64989043d92949fc6ee9a451202e16629be4b36c/Form1.cs but started getting some error message about a null value for the PID and OpenProcess was crashing

Decided to try an earlier build from the release page `Build 2020-10-26T17:58:09.0000000Z` and BINGO everything just worked my app started the bunny hops worked just fine.....

Lets track down this issue between the 2 builds?????

Issue #43 #48 Might be related issue?????

**Comment by NOcturnais** [comment]
I have the same

**Comment by erfg12** [comment]
Make sure the NuGet package "System.Security.Principal.Window" is in your project.

**Comment by erfg12** [comment]
It’s because GetModules was adding to a dictionary that wasn’t instantiated. Fixed in https://github.com/erfg12/memory.dll/commit/75cccc970fd9d1c2d8de4b8db73c7ff2f2cebc90
