### ISSUE TITLE
AoBScan "IndexOutOfRangeException: Index was outside the bounds of the array." when using a variable for the bytes.

### ISSUE THREAD

**Issue by owowhat** [erfg12/memory.dll#124]
When there is a string variable in the search argument it throws the error in the title. This does not happen if a string is hardcoded.

**Comment by erfg12** [comment]
Needs more information. Please give an example of a working and non-working code.

**Comment by owowhat** [comment]
> Needs more information. Please give an example of a working and non-working code.

Non-working code:
`long firstScanResult = m.AoBScan(scanBytes, true, false).Result.FirstOrDefault();`
Working code:
`long firstScanResult = m.AoBScan("01 02 03 04 05", true, false).Result.FirstOrDefault();`

In the first code snippet, scanBytes is a string with the value "01 02 03 04 05".

**Comment by erfg12** [comment]
That can’t be the reason. They’re identical.

**Comment by owowhat** [comment]
> That can’t be the reason. They’re identical. Unless that string was declared in a weird way.
> 
> You need to debug the aob scan method and see exactly which line and variable it has a problem with.

Since commenting, I've been on and off of this problem over some days. I finally noticed that the issue was just a trailing space at the end of my variable, meaning scanBytes would actually be a string with the value "01 02 03 04 05 ".
