### ISSUE TITLE
Is GPL the correct license

### ISSUE THREAD

**Issue by LinAGKar** [erfg12/memory.dll#125]
This project it licensed under the GPL, however it is linked to by some proprietary programs, with the seeming knowledge of the project, and this is something the GPL prohibits. The GPL requires anyone distributing programs linking to it to also include the source code (or a written offer for it), under a license which imposes no additional restriction compared to the GPL. If memory.dll is intended to be used by proprietary software (without having granted them an explicit exception), it would be better to relicense it as LGPL (which requires derivative works to also be LGPL/GPL, but does not restrict programs linking to it), or even a permissive license such as MIT or BSD.

**Comment by erfg12** [comment]
Thank you for this.
