### ISSUE TITLE
Is it possible to provide Using Named Pipes Sample Trainer Code！THK

### ISSUE THREAD

**Issue by HOHOD20XX** [erfg12/memory.dll#130]
Is it possible to provide Using Named Pipes Sample Trainer Code！THK

**Comment by erfg12** [comment]
https://github.com/erfg12/memory.dll/blob/master/Test/TestApp/MemoryTestApp/Classes/Processing.cs#L140

https://github.com/erfg12/memory.dll/wiki/Make-a-Named-Pipe-DLL-(Cplusplus)

https://github.com/erfg12/memory.dll/wiki/Using-Named-Pipes

**Comment by erfg12** [comment]
No reply, closing. Re-open if you have more questions, thank you.
