### ISSUE TITLE
Faster AOB

### ISSUE THREAD

**Issue by Mochongli** [erfg12/memory.dll#131]
https://github.com/Reloaded-Project/Reloaded.Memory.SigScan

**Comment by hollow87** [comment]
Thank you for this I have adjusted FindPattern in PR #134 
The results are now very comparable to that project in fact the only benchmark memory.dll does did not beat prior and is now very comparable was the `WorstCaseScenario` benchmark

Here is the benchmark of `WorstCaseScenario`
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.19044
Intel Core i7-3930K CPU 3.20GHz (Ivy Bridge), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=6.0.200-preview.22055.15
  [Host] : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT
  Core   : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT

Job=Core  Runtime=Core  

```
|    Method |      Mean |     Error |    StdDev |             Speed |
|---------- |----------:|----------:|----------:|------------------ |
|  Compiled |  4.367 ms | 0.0326 ms | 0.0305 ms | 686.9690300685673 |
|    Simple | 44.617 ms | 0.1579 ms | 0.1400 ms |  67.2380517696611 |
| MemoryDll |  5.084 ms | 0.1031 ms | 0.1227 ms | 590.0356574093295 |

Here is the benchmark `LongPatternWithMaskEnd`
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.19044
Intel Core i7-3930K CPU 3.20GHz (Ivy Bridge), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=6.0.200-preview.22055.15
  [Host] : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT
  Core   : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT

Job=Core  Runtime=Core  

```
|    Method |     Mean |     Error |    StdDev |              Speed |
|---------- |---------:|----------:|----------:|------------------- |
|  Compiled | 2.254 ms | 0.0160 ms | 0.0134 ms |  1395.399025656782 |
|    Simple | 3.626 ms | 0.0342 ms | 0.0303 ms |  867.5678341991571 |
| MemoryDll | 2.018 ms | 0.0457 ms | 0.0508 ms | 1558.5944292839258 |

As you can see the results are very similar, nothing very drastic either way.

**Comment by erfg12** [comment]
merged
