### ISSUE TITLE
Sub modules not resolving to the correct address.

### ISSUE THREAD

**Issue by timunrue** [erfg12/memory.dll#15]
I'm running into an issue when trying to use the library to access an address like:
`"base.PrintScriptCallstack+0x57BAC"`

It appears to return the same results as:
`"base+0x57BAC"`

Is this expected behavior? Or am i doing something wrong?

**Comment by hollow87** [comment]
Try omitting the "base." So just "PrintScriptCallstack+0x57BAC"

**Comment by timunrue** [comment]
Thanks for taking the time to respond, love your project.
I tried that and got the same result.  Here is the list of modules according to Cheat Engine:
![](https://i.imgur.com/DUtCtxE.png)


Is there any way to see what the resolved address is using the library?

**Comment by hollow87** [comment]
Since that is an export you could either read the export table manually or you could try using `GetProcAddress`.  I believe both `GetProcAddress` and the variable `pHandle` are public in this library.
