### ISSUE TITLE
Add GetModuleToPointer

### ISSUE THREAD

**Issue by F7Dex** [erfg12/memory.dll#155]
private List<Module> modules = new List<Module>();
        public Module GetModuleToPointer(long address, int pid)
        {
             modules.Clear();
            foreach (ProcessModule P in Process.GetProcessById(pid).Modules)
            {
                if (address >= (long)P.BaseAddress & address <= ((long)P.BaseAddress + P.ModuleMemorySize))
                {
                    modules.Add(new Module((long)P.BaseAddress, ((long)P.BaseAddress + P.ModuleMemorySize), P.ModuleName));
                    break;
                }
            }
            return modules[0];
        }
        
        
            public class Module
    {
        public long Start { get; set; }
        public long End { get; set; }
        public string Name { get; set; }
        public Module(long start, long end, string moduleName)
        {
            Start = start;
            End = end;
            Name = moduleName;
        }
    }

**Comment by alexvirlan** [comment]
Maybe you should check if the modules list is not empty before returning modules[0].
Something like `return modules.Count == 0 ? null : modules[0];`

**Comment by hollow87** [comment]
Create a PR.
