### ISSUE TITLE
Fix GetCode now work in 32bit&64bit

### ISSUE THREAD

**Issue by F7Dex** [erfg12/memory.dll#156]
public UIntPtr GetCode(string name, string path = "", int size = 8)
        {
            if (mProc.Process == null) return UIntPtr.Zero;

            if (mProc.Is64Bit)
                if (size == 8) size = 16; //change to 64bit

            if (!name.Contains("+") & !name.Contains(",") & !name.Contains("."))
            {
                if (size == 8)
                    return (UIntPtr)Convert.ToUInt32(name, 16);
                else
                    return (UIntPtr)Convert.ToUInt64(name, 16);
            }

            // remove spaces
            if (name.Contains(" "))
                name = name.Replace(" ", "");
            // remove 0x
            if (name.Contains("0x"))
                name = name.Replace("0x", "");

            string newOffsets = string.Empty;
            ulong Mod = 0;
            if (name.Contains("+") | name.Contains("."))
            {
               if (name.Contains("+")) newOffsets = name.Split('+')[1];

                if ((name.StartsWith("base")) | name.StartsWith("main"))
                    Mod = (ulong)mProc.MainModule.BaseAddress;
                else
                    Mod = (ulong)GetModuleAddressByName(name.Split('+')[0]);
            }
              
            if (newOffsets.Contains("-"))
                newOffsets = newOffsets.Replace("-", ",");

            byte[] memoryAddress = new byte[size];

            if (newOffsets.Contains(','))
            {
                string[] offsets = newOffsets.Split(',');
                UIntPtr base1 = (UIntPtr)0;

                ReadProcessMemory(mProc.Handle, (UIntPtr)( Mod + Convert.ToUInt32(offsets[0] , 16) ), memoryAddress, (UIntPtr)size, IntPtr.Zero);
                if (size == 8)
                {
                    long num1 = BitConverter.ToUInt32(memoryAddress, 0); //ToUInt32 causes arithmetic overflow.
                    for (int i = 1; i < offsets.Length; i++)
                    {
                        base1 = (UIntPtr)(Convert.ToUInt32(num1 + Convert.ToUInt32(offsets[i], 16)));
                        ReadProcessMemory(mProc.Handle, base1, memoryAddress, (UIntPtr)size, IntPtr.Zero);
                        num1 = BitConverter.ToUInt32(memoryAddress, 0); //ToUInt32 causes arithmetic overflow.
                    }
                }
                else
                {
                    long num1 = BitConverter.ToInt64(memoryAddress, 0); //ToUInt64 causes arithmetic overflow.
                    for (int i = 1; i < offsets.Length; i++)
                    {
                        base1 = (UIntPtr)(Convert.ToUInt64(num1 + Convert.ToUInt32(offsets[i], 16)));
                        ReadProcessMemory(mProc.Handle, base1, memoryAddress, (UIntPtr)size, IntPtr.Zero);
                        num1 = BitConverter.ToInt64(memoryAddress, 0); //ToUInt64 causes arithmetic overflow.
                    }
                }
                return base1;
            }
            else // no offsets
                if (newOffsets == string.Empty)
                return (UIntPtr)(Mod);
            else
              return (UIntPtr)(Mod + Convert.ToUInt32(newOffsets, 16));
        }

**Comment by hollow87** [comment]
Make a PR
