### ISSUE TITLE
WriteMemory function doesn't work in specifical condition

### ISSUE THREAD

**Issue by Caritusy** [erfg12/memory.dll#167]
**The range of applicability for the issue :**
1.2.25 - 1.2.26

**Reproducing the issue :** 
**1.** Find some data in a not writable non executable area
**2.** Do AobScan on these data
**3.** Try to set any data for these data

**Result:**
WriteMemory Function runs well but the data won't get any change

**Possible reason:**
From the publish release version 1.2.25,seems like something is changed to prevent memory.dll will be delete from antivirus program.
But this feature make memory.dll loss the write premission from some data.

**Temporary solution:**
Roll back to 1.2.24,if you want "mapped" argument in AobScan,complied memory.dll by yourself.

**Comment by Caritusy** [comment]
**A new resolve way:**
Follow the 
https://github.com/erfg12/memory.dll/commit/300edbac9aceb5ab6e23b535d2f051c804b074b3
uncommit it and recomplie it by yourself.
As the developer of memory.dll,the change is prevent memory.dll be delete from nuget due it gets flagged as malware

**Comment by erfg12** [comment]
Windows is for some reason really targeting certain methods in libraries. I was able to submit a new x86 build to NuGet but the x64 one failed for no reason. I will eventually try it again.
