### ISSUE TITLE
OpenProcess

### ISSUE THREAD

**Issue by SnailingGoat** [erfg12/memory.dll#17]
Ok. So I tried to write this memory for this game called Growtopia. It is just a stupid online game for I can practice c# memory manipulation on. When I try to `OpenProcess()` it says the process does not exist (returns false) but the `GetProcessIDFromName()` function is returning some numbers. 

Please help

Best regards Petr Gardas

**Comment by erfg12** [comment]
Show Task Manager > Details for your game.

**Comment by erfg12** [comment]
No response = close issue. You can re-open if you're still having issues.
