### ISSUE TITLE
Can't use memory read/write functions on addresses within module that has name containing "main"

### ISSUE THREAD

**Issue by Auride** [erfg12/memory.dll#172]
I'm trying to create a trainer for the Steam version of Okami HD. I already have a fairly thorough table of memory addresses from Cheat Engine (See [here](https://github.com/Shintensu/OkamiHD-Reverse-Engineering/blob/master/OkamiHD-RE-Table-V0.1.CT)). Most of the important addresses are within the `main.dll` module. I noticed that my addresses weren't being read/written correctly from the trainer I was building following [this tutorial](https://www.youtube.com/watch?v=STPrGJ8eI8Y). I did some more investigating and wrote these lines:

```C#
IntPtr gameBase = memLib.GetModuleAddressByName("okami.exe");
Trace.WriteLine(gameBase.ToString("X"));
UIntPtr mainDLL1000 = memLib.Get64BitCode("main.dll+0x1000");
Trace.WriteLine(((long)mainDLL1000).ToString("X"));
```

The output was the following:
```
7FF6009A0000
7FF6009A1000
```
This indicates that `"main.dll"` was being treated as equivalent to `"okami.exe"` or `"base"`. I looked at the source code and found this line:

https://github.com/erfg12/memory.dll/blob/8dc786dff77ca0dadb1052261529d702793a1301/Memory/memory.cs#L422C67-L422C71
```C#
if (theCode.Contains("base") || theCode.Contains("main"))
                    ReadProcessMemory(mProc.Handle, (UIntPtr)((int)mProc.MainModule.BaseAddress + offsets[0]), memoryAddress, (UIntPtr)size, IntPtr.Zero);
```
This seems to indicate to me that any module which happened to contain "base" or "main" would automatically get converted to the process's base module (okami.exe in this case), which prevents the use of any such module.

Am I understanding this correctly? Is this intended behavior? Is there a workaround?

Thank you!

**Comment by erfg12** [comment]
oh... yeah we probably have to add another condition there, good catch. I'll see if I can add that check.

**Comment by Auride** [comment]
Could you change `.Contains` to `.Equals`? Is there a reason to be more permissive?

**Comment by erfg12** [comment]
Thanks, fixed in https://github.com/erfg12/memory.dll/commit/cabec1a8bc4c9975fea040e9f4e2a2ced93c3a3e
