### ISSUE TITLE
AoB Scan Overflow

### ISSUE THREAD

**Issue by gcsoftware** [erfg12/memory.dll#20]
Mem memLib = new Mem();

memLib.OpenProcess("MyGame");

speedAddr = memLib.AoBScan("0x15000000", 0x10000, ("C7 C7 20 32 02 00 00 00 ?? ?? ?? ?? 5D 5E 89 EB")).Result;

Used to work fine on previous versions of memory.dll.

I receive an unhandled exception:
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr..ctor(Int64 value)
   at Memory.Mem.<AoBScan>d__116.MoveNext()

**Comment by hollow87** [comment]
The 2nd parameter has been changed from length to end address.

**Comment by gcsoftware** [comment]
Adjusted the length to end address and still receiving the exception.

**Comment by erfg12** [comment]
Why does the array have parenthesis?

**Comment by erfg12** [comment]
No response. You can re-open if problem not solved.
