### ISSUE TITLE
Updated AoBScan - but not the Parameterlist Comments

### ISSUE THREAD

**Issue by Proktologe** [erfg12/memory.dll#24]
AoBScan function was updated, but the function comments were not. Could you shortly explain the usage of the parameters
"string code" and
"long end" 

thx

**Comment by erfg12** [comment]
If you're using the one in NuGet that is an older version. atm we're working on a version that is faster, and simpler to use in the repo. Compile that one and give it a test. If you want to know more about the new function structures: https://github.com/erfg12/memory.dll/wiki/AoB-Scanning

**Comment by erfg12** [comment]
No response in 14 days. I'm gonna close this. You can re-open it if you are still having issues.
