### ISSUE TITLE
Unable to write memory to process

### ISSUE THREAD

**Issue by kaliiks** [erfg12/memory.dll#25]
I'm trying to write memory to process with
`MemLib.writeMemory("Minecraft.Windows.exe+1FC2490", "string", "Noclip");`
When I search for 'noclip' in cheat engine i get Minecraft.Windows.exe+1FC2490 with string value 'noclip' and when I change it to Noclip it enable noclip, but when I do it in memory.dll it's not working

Here's how I get the process
`int gameProcId = MemLib.getProcIDFromName("Minecraft.Windows");
            if(gameProcId != 0)
            {
                loaded = true;
                if (!MemLib.OpenProcess(gameProcId.ToString()))
                {
                    MessageBox.Show("Fail");
                }
                else
                {
                    MessageBox.Show("ok");
                }
                label1.Text = "Process ID: " + gameProcId.ToString();
                

            }
            else
            {
                MessageBox.Show("not found");
            }`

**Comment by erfg12** [comment]
Need a little bit more info.

1. Are you running it with administrative privileges?
2. Does it give you the proper process ID?
