### ISSUE TITLE
Object reference not set to instance of an object

### ISSUE THREAD

**Issue by Difento** [erfg12/memory.dll#27]
I got error when i write memory
"Object reference not set to instance of an object"

This my code

Public Mem Memori = new Mem()
Private void Form1_load(object sender, eventarg e)
{
Memori.OpenProcess("RF_Online.bin")
Memori.writeMemory("base+0x025A631C,0x096", "byte", "0xff")
}

**Comment by erfg12** [comment]
Memori.OpenProcess("RF_Online.bin") <-- this is probably incorrect.

Show me the process of your game in Task Manager > Details tab.

**Comment by nirinium** [comment]
I think it is a .bin file. Not sure if main proc is running from that.. Definitely agree with erfg. Post results of the process name and we can go from there.

**Comment by hollow87** [comment]
I just got the game he has based on process name.  Yes RF_Online.bin is main process

**Comment by Difento** [comment]
problem is solved, i changed RF_Online.bin to 0400000
