### ISSUE TITLE
System.Reflection.TargetInvocationException - AOB Scanning in Windows Forms

### ISSUE THREAD

**Issue by Sadulisten** [erfg12/memory.dll#29]
![alt text](https://i.imgur.com/BSnSPsw.png)

This is how I try to call your .dll
```cs
private async void button3_Click(object sender, EventArgs e)
		{
			Mem m = new Mem();
			int processId = Process.GetProcessesByName(comboBox1.Text).FirstOrDefault().Id;

			if (m.OpenProcess(processId))
			{
				this.Text = "Scanning ...";

				Task<IEnumerable<long>> task = m.AoBScan(richTextBox1.Text.Trim());
				var result = await task;
				m.closeProcess();

				foreach (long address in result)
				{
					dataGridView1.Rows.Add(address);
				}
			}
			else
			{
				MessageBox.Show("Could not openprocess!");
			}
		}
````

The inner exception shows this
![alt text](https://i.imgur.com/wxvnujn.png)

The process ID is not empty, and the pattern is also not empty.
I run the program as administrator etc.

Hopefully I am just doing something wrong, love your project eitherway!

**Comment by Sadulisten** [comment]
EDIT:

Turns out the exception was process specific, so probably not an issue.
What does it mean though?

Sorry for the inconvenience

**Comment by erfg12** [comment]
This has nothing to do with Memory.dll

Join our Discord if you have questions about C#.
