### ISSUE TITLE
Overflow Exception with 32Bit AOBScanning on some machines

### ISSUE THREAD

**Issue by Git-Curve** [erfg12/memory.dll#31]
Okay so I tested the 32Bit AoBScanning on multiple Machines and on some it worked just fine and on some it threw a Overflow Excption.

Here is the used test Code:

`MemLib.OpenProcess("Test32BitProcess");`
`var adr = MemLib.AoBScan("D9 40 30 D9 05 ?? ?? ?? ?? DF F1 DD D8 77 1D 8B 43 18").GetAwaiter().GetResult() + 0x9;`
`Console.WriteLine(adr);`
`if(MemLib.writeMemory(adr.ToString("X"), "bytes", "0x90 0x90")) {`
`Console.WriteLine("Success");`
`}`
`Console.WriteLine("Done");`

The build Configuration was:
Platform: Any CPU
Preffer 32 Bit: Yes
Framework: .Net Framework 4.7.1

**Comment by erfg12** [comment]
Did they AoB scan always return 1 result? Is it possible it returned a bad address and then you added 0x9 to it and it crashed because of that?

I would make the variable for the scan, but then below that add the + 0x9 to be sure it's not the AoB scan crashing it.

**Comment by Git-Curve** [comment]
I already did that before, it still throws the same exception

**Comment by Git-Curve** [comment]
And the AOBScan didnt even return a result, it crashed before it gave results :D

**Comment by erfg12** [comment]
Using newest memory.dll I assume? Do this instead:

    if (MemLib.OpenProcess("Test32BitProcess")) {
        var adr = MemLib.AoBScan("").GetAwaiter().GetResult() + 0x9;
        long myAoBScan = (await MemLib.AoBScan("D9 40 30 D9 05 ?? ?? ?? ?? DF F1 DD D8 77 1D 8B 43 18", false, true, codeFile)).FirstOrDefault();
        adr = myAoBScan + 0x9;
        Console.WriteLine(adr);
        if(MemLib.writeMemory(adr.ToString("X"), "bytes", "0x90 0x90"))
        Console.WriteLine("Success");
    }
    Console.WriteLine("Done");

**Comment by erfg12** [comment]
No reply in months. Closing
