### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by Zeta314** [erfg12/memory.dll#32]
Hi there. When I use the AoBScan to scan for a mask (the world pointer), it throws me an IndexOutOfRangeException.

`long WorldPTR = memory.AoBScan("48 8B 05 ? ? ? ? 45 ? ? ? ? 48 8B 48 08 48 85 C9 74 07").Result.First();`

I tried
`long WorldPTR = (await memory.AoBScan("48 8B 05 ? ? ? ? 45 ? ? ? ? 48 8B 48 08 48 85 C9 74 07")).Result.First();` as the examples says but it gives error saying it's not an asyncronous task. HEEEEELP.

**Comment by Zeta314** [comment]
Tried also `long WorldPTR = memory.AoBScan("0x0000000000000000", 0x7fffffffffffffff,
                        "48 8B 05 ? ? ? ? 45 ? ? ? ? 48 8B 48 08 48 85 C9 74 07").Result;`
but it throws the same IndexOutOfRangeException.

**Comment by LuanDevecchi** [comment]
created a pull request that fixes this btw
