### ISSUE TITLE
how can I add "registersymbol"?

### ISSUE THREAD

**Issue by sesey** [erfg12/memory.dll#33]
CheatEngine also has the "registersymbol" feature.
how can I add "registersymbol" and how can I get this adrese?
I use "CreateCodeCaves" feature, but how can I do it here?

`mov eax,edx`

I need to reach my "eax" value.

**Comment by erfg12** [comment]
Why don't you just use a variable?
int64 myAddress = 0x88888888; //?

**Comment by sesey** [comment]
How do I convert the assembly code to hexadecimal when I use a variable?

**Comment by erfg12** [comment]
You have to look at this from a C# perspective and not from assembly. Go to that address and note the byte differences as you cannot write ASM in C#. Make changes via CE and once again note the byte changes.

You can write/read bytes in C#, so do that.

**Comment by sesey** [comment]
I know that, but the method you say is not useful.

**Comment by hollow87** [comment]
CreateCodeCave will allocate memory with read write execute permissions.  It will also give you the address at which it was allocated.  As it does not include an assembler at this time it is up to you to create the machine code from assembly one way or another.  In terms of reading "eax" you could copy the value of eax to a specific address in that allocated memory then read/write to that address

**Comment by erfg12** [comment]
No response from op.
