### ISSUE TITLE
AOBscan

### ISSUE THREAD

**Issue by yhyamak** [erfg12/memory.dll#34]
thanks alot for this tool ,
its really helpful
could you please put a code for AOBSCAN in VisualBasic.net?

**Comment by hollow87** [comment]
AoBScan is not just c# you can use any .net language.

**Comment by yhyamak** [comment]
thanks ...
but there is error :
Overload resolution failed because no accessible 'AoBScan' can be called without a narrowing conversion

so if you put the code i will be grateful to you

**Comment by yhyamak** [comment]
thanks ...
after trying some codes:

 Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim m As New Memory.Mem
        Dim pid = m.getProcIDFromName("Notepad++")
        Dim openproc = False
        If pid > 0 Then
            openproc = m.OpenProcess(pid)

        End If
        If openproc Then
            Dim st As Long
            Dim en As Long
            Dim se As String
            st = "00000000"
            en = "90000000"
            se = "D0 07 D3 00 B0 EC 6A 01 D8 EC 6A"

            Dim addr = Await m.AoBScan(st, en, se, True, True)
   
         MsgBox(addr(0))
        End If
    End Sub

this work for me
