### ISSUE TITLE
Can't get AoBScan to work

### ISSUE THREAD

**Issue by hitmanex** [erfg12/memory.dll#39]
i'm probably doing something wrong

```
 var x = mem.AoBScan("6D 3A 2F 2F 75 72 6C 2F 53 74 65 61 6D 49 44 50 61 67 65 2F ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??").GetAwaiter().GetResult();
Console.WriteLine(x);
```
![gyqhljx 1](https://user-images.githubusercontent.com/34111698/45788550-41f4d900-bc49-11e8-869a-479750554e17.png)

`System.Linq.OrderedEnumerable`2[System.Int64,System.Int64]`

**Comment by erfg12** [comment]
Did u try the latest source?

**Comment by hitmanex** [comment]
the nuget package

**Comment by erfg12** [comment]
Ok, we’re currently working on fixing the aob scan. I recommend compiling the code and test that.

**Comment by hollow87** [comment]
Well that is not an error that is what you get when you print an ordered enumerable.  AoB return type is an `IEnumerable` to return multiple results at once. Try looping through each element of  the `IEnumerable` like you do in your lua code instead of just calling `.ToString()` on it.

**Comment by hitmanex** [comment]
```
 var iterate = x.GetEnumerator();
while (iterate.MoveNext())
Console.WriteLine(iterate.Current);
```

it's just blank. there's something wrong

**Comment by hollow87** [comment]
First off I would have used a foreach loop less code easier to read.  Second thing if the memory that needs to be searched is writable please pass true for that argument.  If the memory is just read and executable then it should be working fine.  Please output the value of `x.Any()`

**Comment by hitmanex** [comment]
`var x = mem.AoBScan("6D 3A 2F 2F 75 72 6C 2F 53 74 65 61 6D 49 44 50 61 67 65 2F ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??", true).GetAwaiter().GetResult();`

` Console.WriteLine(x.Any());` ouputs

`True`

**Comment by hollow87** [comment]
If `x.Any()` returns true it has values and you can loop through it or take the first one etc

**Comment by hitmanex** [comment]
i got it to work. the output was int64 i converted it to hex and the values are accurate

thank you
