### ISSUE TITLE
ASM instruction replacement and code caves

### ISSUE THREAD

**Issue by erfg12** [erfg12/memory.dll#4]
NOTE: Try using C++ dll with named pipes to send ASM in string format, and parse in C++ to real ASM, then execute the function.

**Comment by hollow87** [comment]
I have code caves implemented in my trainer framework library, if you want take a look and take from there, however I never got around to implementing an assembler in my project.

https://github.com/hollow87/HollowTrainerFramework

The open source license is 3-clause BSD.
 
Need any help with this project feel free to let me know

**Comment by erfg12** [comment]
I'm really just looking to write ASM.

**Comment by erfg12** [comment]
Thanks @hollow87 for adding the new code cave system. I would still like some way to inject ASM natively. I'll leave this open for now till we figure something out.
