### ISSUE TITLE
OpenProcess always return false

### ISSUE THREAD

**Issue by Xwilarg** [erfg12/memory.dll#43]
Hi,

I made this little code:
```Cs
Process p = Process.GetProcessesByName("WWAHost")[0];
Mem mem = new Mem();
Console.WriteLine(mem.OpenProcess(p.Id));
````

But it always display 'false' in the console.
I tried with other process but it doesn't work too.
I launched the program with administrator rights.

I'm on Windows 10.

Thanks in advance,

**Comment by erfg12** [comment]
Why not do mem.OpenProcess("WWAHost"); ?
Also, why are you posting for support in Issues? In our Wiki it states if you need support, join our Discord and talk to us if you need help getting started. We open issues for things that need to get fixed.

**Comment by Xwilarg** [comment]
I'm sorry, I didn't see that there was a Discord.
About the Process class, I was using it as a proof that GetProcessesByName find the process.

**Comment by erfg12** [comment]
ok, well join our Discord so we can help you.
