### ISSUE TITLE
Pointer always returns 0

### ISSUE THREAD

**Issue by Dekirai** [erfg12/memory.dll#44]
if (openProc)
                {

                    int charid = memread.readByte("TekkenGame-Win64-Shipping.exe+0x33FE0E0,0x10,0x38,0x0,0x0,0x14");
                    MessageBox.Show(charid.ToString());

                    if (charid.ToString("X") == "09")
                    {
                        MessageBox.Show("Got value " + charid.ToString("X"));
                    }
                    else
                    {
                        MessageBox.Show("Value not known");
                    }
                }
![Issue](https://shinzuya.s-ul.eu/JRFyGCzy.png)
![Issue2](https://shinzuya.s-ul.eu/ygQCkvQf.png)
Does anybody know why it always returns 0, when it should be 9?

**Comment by erfg12** [comment]
Need more information. Did you:
1) Raise privs to admin lvl
2) Uncheck the prefer 32bit checkbox

Also, for the read byte, use "base" instead of "TekkenGame-Win64-Shipping.exe".

**Comment by Dekirai** [comment]
1. Yes I did
2. I can't because I'm working with DiscordRPC and when I uncheck this, I'll get an error. (System.BadImageFormatException)

When I use base instead of the process name, I'll also get an error. (System.NullReferenceException)

**Comment by erfg12** [comment]
It's a 64bit game, so you gotta compile your trainer in 64bit to read 64bit memory addresses.

**Comment by Whrothus** [comment]
When you use target framework Core3.0 
Other things work

**Comment by erfg12** [comment]
@Whrothus some functions are designed to return 0 on failure. As long as your trainer has raised privileges, opens the process and you use the CE offset structure correctly, everything should work out. Memory.dll was designed for .NET Framework v4.0+

Anything beyond this scope is considered experimental.
