### ISSUE TITLE
AoBScan Mask

### ISSUE THREAD

**Issue by nandobfmv** [erfg12/memory.dll#47]
Is there any way to make the "??" mask return only values higher than "0"? That's because I have some values in my AoB that keeps changing randomly but their values are always higher than 0, but when I use "??" mask, I get thousands of results where "??" is replaced with 00, if it only accept values higher than 00 it would return only one result. 

btw, thank you for this awesome project!

**Comment by erfg12** [comment]
tbh, you could download the memory.dll source code and make AoB scan do just that. I don't think there is such an option built in.
