### ISSUE TITLE
AoB Scanning memory usage

### ISSUE THREAD

**Issue by nandobfmv** [erfg12/memory.dll#49]
When doing a full range scan 0x00000000, 0x07FFFFFFF the amount of RAM used by the trainer scales up to 2Gb, then, when the scan is done, it returns to 30Mb. Is that normal?

**Comment by Sadulisten** [comment]
Yes its normal :)

**Comment by erfg12** [comment]
An AoB scan uses a pool of workers to achieve fast results.
