### ISSUE TITLE
AoB scan is not work

### ISSUE THREAD

**Issue by JKstring** [erfg12/memory.dll#5]
MemLib.AoBScan("sao_hr.exe+20000000", 40000000, "32 189 160 10 1");
MemLib.AoBScan("sao_hr.exe", 40000000, "32 189 160 10 1");
MemLib.AoBScan("sao_hr", 40000000, "32 189 160 10 1");
MemLib.AoBScan("140000000", 40000000, "32 189 160 10 1");
MemLib.AoBScan("0x140000000", 0x40000000, "32 189 160 10 1");
MemLib.AoBScan("sao_hr.exe", 0x40000000, "32 189 160 10 1");
========================================
The exception is thrown all over it

64 bit game
MemLib.AoBScan("0x140000000", 0x40000000, "32 189 160 10 1");
MemLib.AoBScan("0x140000000", 0x40000000, "20 BD A0 0A 01");
throw exception uint32 too small
Am I using it wrong?

@erfg12

**Comment by erfg12** [comment]
One problem is you can't use integers to represent hex. Use hex bytes for your AoB scan string.

Also, post your VS console log while debugging your solution.

**Comment by JKstring** [comment]
thank you ,it run

MemLib.AoBScan("0000000000000000", 0x7fffffffffffffff, "20 BD A0");
[DEBUG] memory scan starting... (base:0x0000000140000000 max:000000027e997000
search only be between base and max?
not like Cheat Engin?

and
MemLib.AoBScan("base", 0x7fffffffffffffff, "20 BD A0");

Program is operating at Administrative level. Now opening process id #11332.
Now storing module addresses for process id #11332.
引发的异常:“System.AggregateException”(位于 mscorlib.dll 中)

"base" can not use?

my English is not good, please forgive me

@erfg12

**Comment by erfg12** [comment]
Doesn't matter if it runs before base. I guarantee the address you are looking for is not located before the base address as your program launch address and base address are the same address. It literally cannot be before it, it's not possible.

Did you properly open the game process? Show me some code.

**Comment by JKstring** [comment]
Maybe the data I'm looking for is greater than max?

`
static bool is_open = false;
private void Form1_Load(object sender, EventArgs e)
        {
            int a = Win32.User32.RegisterHotKey(Handle, 100, 0, Win32.User32.VkKeyScan((byte)'`'));
            System.Diagnostics.Process.GetCurrentProcess().PriorityClass = System.Diagnostics.ProcessPriorityClass.High;
            Win32.User32.SetActiveWindow(ip);
            Win32.User32.SetForegroundWindow(ip);
            Win32.User32.ShowWindow(ip, Win32.User32.SHOW_OPENWINDOW);
            openGame();
        }

private void openGame()
        {
            gameProcId = MemLib.getProcIDFromName("sao_hr");
            if (gameProcId > 0)
            {
                bool is_ok = MemLib.OpenProcess(gameProcId);
            }
        }

private void TestFunction()
        {
            if (gameProcId > 0)
            {
                var x = MemLib.AoBScan("base", 0x7fffffffffffffff, "20 BD A0");//MemLib.AoBScan("0x0000000000000000", 0x7fffffffffffffff, "20 BD A0");
                x.Wait();
                var t = x.Result;
                //int c = MemLib.readByte("sao_hr.exe+00AEAD58,48,100,0,1B0,510,9");
                int c = MemLib.readByte("2346cc29");
                if (c == 2)
                    MessageBox.Show("1");
                else
                    MessageBox.Show("0:" + c);
            }
        }

protected override void WndProc(ref Message m)
        {
            const int WM_HOTKEY = 0x0312;
            switch (m.Msg)
            {
                case WM_HOTKEY:
                    switch (m.WParam.ToInt32())
                    {
                        case 100:    
                            is_open = !is_open;
                            if (is_open) {
                                if (t == null || !t.IsAlive)
                                {
                                    (t = new System.Threading.Thread(() => { TestFunction(); /*AutoSSC();*/ })).Start();
                                }
                            }     
                            break;
                    }
                    break;
            }
            base.WndProc(ref m);
        }

private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {
            Win32.User32.UnregisterHotKey(Handle, 100);
            MemLib.closeProcess();
        }
`

I think I know,It's OK to use "base+0".

Thanks for your help!

**Comment by muhahah4** [comment]
`        /// <summary>
        /// Convert code from string to real address. If path is not blank, will pull from ini file.
        /// </summary>
        /// <param name="name">label in ini file</param>
        /// <param name="path">path to ini file</param>
        /// <param name="size">size of address (default is 16)</param>
        /// <returns></returns>
        private UIntPtr get64bitCode(string name, string path, int size = 16)
        {
            string theCode = LoadCode(name, path);
            if (theCode == "")
                return UIntPtr.Zero;
            string newOffsets = theCode;
            if (theCode.Contains("+"))
                newOffsets = theCode.Substring(theCode.IndexOf('+') + 1);

            byte[] memoryAddress = new byte[size];

            if (!theCode.Contains("+") && !theCode.Contains(",")) return new UIntPtr(**Convert.ToUInt64**(theCode, 16));`

**Comment by erfg12** [comment]
Thanks @muhahah4 

Try scanning again @JKstring

**Comment by JKstring** [comment]
Exception too.The test code is the 5F

target platform is X64 ,only use "base+0"
target platform is X86 ,always Exception

Exception:
```
Program is operating at Administrative level. Now opening process id #10932.
Now storing module addresses for process id #10932.
引发的异常:“System.AggregateException”(位于 mscorlib.dll 中)
```

I have a part of the unsafe code code that must run in X86, I temporarily disable it, can memory.dll modify the X64 program on the X86 target platform?

The memory I search may not be in game but in DirectX DLL, so can the search address be greater than max address?

@erfg12

**Comment by hollow87** [comment]
If the target process is x64 you have to target the x64 architecture.

**Comment by erfg12** [comment]
Exactly what @hollow87 said. When compiling your source code, follow this guide: https://github.com/erfg12/memory.dll/wiki/64bit-Games

**Comment by erfg12** [comment]
Exactly what @hollow87 said. When compiling your source code, follow this guide: https://github.com/erfg12/memory.dll/wiki/64bit-Games

**Comment by JKstring** [comment]
OK.Thank help!
@erfg12 @hollow87

**Comment by erfg12** [comment]
So, is everything working? If so, I'll close this issue out.
