### ISSUE TITLE
High CPU usage with FreezeValues

### ISSUE THREAD

**Issue by Seremo** [erfg12/memory.dll#53]
Hi, If we using FreezeValue function our app will start using a lot of CPU resources(on my i5-8400 more than 50%).
Im enclosing the screenshot and counting on a fast fix :)

![cpu usage](https://user-images.githubusercontent.com/48060122/53499012-c3c61980-3aa7-11e9-9707-a0a635add1bb.png)

**Comment by erfg12** [comment]
Semi fixed: 14364f5c28d30d82607ff6e6590f0d3128a2ae1f
