### ISSUE TITLE
64bit games supported？Really？

### ISSUE THREAD

**Issue by zengfr** [erfg12/memory.dll#58]
i see project code
https://github.com/erfg12/memory.dll/blob/master/Memory/memory.cs
mainModule = theProc.MainModule;

if in 64 is error "A 32 bit processes cannot access modules of a 64 bit process"

**Comment by erfg12** [comment]
Read this article https://github.com/erfg12/memory.dll/wiki/64bit-Games

**Comment by erfg12** [comment]
no reply, closing.
