### ISSUE TITLE
need support to read 16bytes long string in 64 bit system

### ISSUE THREAD

**Issue by ccorzlol** [erfg12/memory.dll#6]
Hi Erfg,

Thank you for making this great project and I'm right now having issue when read string from 64 bit system. The function I'm using is readString(string code, string file), which seems to only can be fed in 32bit address. Would it be possible to update it to support fed in 64bit address?

Regards,
ccorzlol

**Comment by ccorzlol** [comment]
for example the address 0x0000019a3ce803f0 is the starting address trying to read string from...and the exception would be address 0x0000019a3ce803f0 too long for readString()

**Comment by erfg12** [comment]
Uhm... strange. The string "code" auto adjusts to 64bit when the application is 64 bit (not the machine). Here is the code that reads it.

https://github.com/erfg12/memory.dll/blob/master/Memory/Class1.cs#L884

I assume your structure is `string test = m.readString("0x0000019a3ce803f0");` ?

**Comment by erfg12** [comment]
You might have to download the memory.dll source, compile the .dll and use that when debugging so you can see the exact line that is causing the issue in memory.dll.

**Comment by ccorzlol** [comment]
once I trim the address to 0x3ce803f0, it works just fine...will try to debug using source to see which line is causing issue. thank you for the timely reply!

**Comment by erfg12** [comment]
Is your game 64bit?

**Comment by ccorzlol** [comment]
yes, when check in hex editor it shows PE d†..

**Comment by ccorzlol** [comment]
I'm using 

https://superuser.com/questions/103071/quick-way-to-tell-if-an-installed-application-is-64-bit-or-32-bit

```
If you have a hex editor program, just open your file with it and shortly after the standard header intro stuff (like "This program cannot be run in DOS mode...") you will see either

"PE..L" (hex code: 504500004C) = 32 bit

or

"PE..d†" (hex code: 504500006486) = 64 bit
```

**Comment by ccorzlol** [comment]
This is the error I'm getting. Will debug and revert back here.

> _An exception of type 'System.OverflowException' occurred in mscorlib.dll but was not handled in user code
>Additional information: Value was either too large or too small for a UInt32._

**Comment by erfg12** [comment]
You can also uncomment the debug code I was using to see if memory.dll recognizes it as 64bit.

**Comment by ccorzlol** [comment]
```
        private UIntPtr get64bitCode(string name, string path, int size = 16)
        {
            string theCode = LoadCode(name, path);
            if (theCode == "")
                return UIntPtr.Zero;
            string newOffsets = theCode;
            if (theCode.Contains("+"))
                newOffsets = theCode.Substring(theCode.IndexOf('+') + 1);

            byte[] memoryAddress = new byte[size];

            if (!theCode.Contains("+") && !theCode.Contains(",")) return new UIntPtr(Convert.ToUInt32(theCode, 16));    <<<this line is causing issue
```

**Comment by ccorzlol** [comment]
thecode value is "19A3CE803F0", so return UIntPtr(Convert.ToUInt32(theCode, 16)) cause the exception.

**Comment by erfg12** [comment]
If you change ToUInt64 would it work? (not sure how I missed that)

**Comment by ccorzlol** [comment]
works like a charm! thank you for all the help!

**Comment by erfg12** [comment]
Thanks, I'm gonna fix that now.

**Comment by erfg12** [comment]
New version 1.2.10 pushed to NuGet.

**Comment by hollow87** [comment]
The issue with the AOB Scan #5 might be related based on this @muhahah4 comment. https://github.com/erfg12/memory.dll/issues/5#issuecomment-347288555

**Comment by erfg12** [comment]
Oops.
