### ISSUE TITLE
Big Endian memory reading and writing

### ISSUE THREAD

**Issue by Urahara3000** [erfg12/memory.dll#62]
Well, I'm already a longtime user of your memory manipulation DLL, and currently I can say that it's almost perfect, only one detail is missing from it, the option of writing and reading memory in the Big Endian type, the types that are missing from the DLL are:

2 Bytes Big Endian
4 Bytes Big Endian
Float Big Endian

Could you create a function for each type of this, both for reading and writing ?

It would be a very interesting addition to your DLL, well, for sure you will ask, but why the hell do i need to add Big Endian to my DLL, the answer is simple, there are some emulators that use the Big Endian type, as well as the PS3's RPCS3 and Wii U's Cemu, if you can add these functions to your DLL, I would be very grateful, me and everyone who uses your DLL in RPCS3 and Cemu games.

**Comment by theclub654** [comment]
just swap the bytes before you write or read them

**Comment by xCENTx** [comment]
Just gonna comment and Reopen this. A simple byte swap is not enough to write to unprotected memory via RPCS3. I have spend most of the morning messing about with this. Reading memory? Fine works like a charm. But you simply cannot swap bytes and write to memory and have it succeed. RPCS3 either crashes or nothing happens at all

**Comment by Urahara3000** [comment]
> Just gonna comment and Reopen this. A simple byte swap is not enough to write to unprotected memory via RPCS3. I have spend most of the morning messing about with this. Reading memory? Fine works like a charm. But you simply cannot swap bytes and write to memory and have it succeed. RPCS3 either crashes or nothing happens at all
> 
> The following method works just fine to read the value at an address and parse it from 4byte little endian to 4byte big endian. This will show a decimal value as seen in game.
> 
> ```
> //Reads Current Souls and displays the value via Label
> BigInteger parseSoulsAddr = BigInteger.Parse("3301E8098", NumberStyles.HexNumber);
> var SoulsAddr = parseSoulsAddr.ToString("X");
> var SoulsAddrValue = m.ReadUInt(SoulsAddr);
> var CURRENT_SOULS = SwapBytes(SoulsAddrValue);
> CurrentSouls_Label.Text = "CURRENT SOULS: " + Convert.ToString(CURRENT_SOULS);
> ```
> 
> The following write methods have all failed and crashed my emulator. I've lost count on how many times I've had to restart the emulator , just t freeze it again.
> 
> ```
> BigInteger parseSoulsAddr = BigInteger.Parse("3301E8098", NumberStyles.HexNumber);
> var SoulsAddr = parseSoulsAddr.ToString();
> var NEW_SOULS = SwapBytes(1337);
> 
> //m.WriteMemory(SoulsAddr, "int", Convert.ToString(NEW_SOULS)); /// FAILS
> //m.WriteMemory("0x3301E8098", "uint", "100"); /// FAILS
> //if (m.WriteMemory("0x3301E8098", "int", "100")) /// FAILS
> 
> //NewAgeSoftware Method
> BigInteger parseSoulsAddr = BigInteger.Parse("3301E8098", NumberStyles.HexNumber);
> string hex = $"0x{parseSoulsAddr:X8}";
> var NEW_SOULS = SwapBytes(100); // Where is this used?
> m.WriteMemory(hex, "int", "100"); // Again , Fails
> ```
> 
> Here is the used method "SwapBytes"
> 
> ```
> public uint SwapBytes(uint x)
> {
>     return ((x & 0x000000ff) << 24) +
>            ((x & 0x0000ff00) << 8) +
>            ((x & 0x00ff0000) >> 8) +
>            ((x & 0xff000000) >> 24);
> }
> ```
> 
> Demon Soul's via RPCS3
> 
> EDIT:
> 
> I managed to get this working with a bit of help from "Ohm" from the discord community. He believes swapbytes or writememory might be messed up. I have included my version of SwapBytes (Found on stack exchange)
> 
> Here is my working method to write to RPCS3 Memory (again Credit to "Ohm" for his helping)
> 
> ```
> BigInteger parseSoulsAddr = BigInteger.Parse("3301E8098", NumberStyles.HexNumber);
> string hex = $"0x{parseSoulsAddr:X8}";
> int intValue = 100;
> byte[] intBytes = BitConverter.GetBytes(intValue);
> Array.Reverse(intBytes);
> byte[] result = intBytes;
> m.WriteBytes(hex, intBytes);
> ```

Thank you very much for the reply !
