### ISSUE TITLE
aob scan always return 0000000 but cheatengine found adresse

### ISSUE THREAD

**Issue by bozoweed** [erfg12/memory.dll#7]
hi my aobscan always return 00000 i don't know why

this is my function
 long fuel = m.AoBScan("0x00000000", 0x7FFFFFFF, "?? ?? ?? ?? 0A D7 A3 3E 66 66 06 40 85 6B 80 3F A0 77").Result;

i have try
long fuel = m.AoBScan("0x03000000", 0x70000000, "?? ?? ?? ?? 0A D7 A3 3E 66 66 06 40 85 6B 80 3F A0 77").Result;
but same result can some one help me ?

**Comment by bozoweed** [comment]
and this too .. 
long fuel = m.AoBScan("0x0000000000000000", 0x7FFFFFFFFFFFFFFF , "?? ?? ?? ?? 0A D7 A3 3E 66 66 06 40 85 6B 80 3F A0 77").Result;

**Comment by bozoweed** [comment]
lastlely this for get lowest min value .. string min = m.getMinAddress().ToString("x8");
              
                long fuel =  m.AoBScan(min, 0x7FFFFFFFFFFFFFFF, "?? ?? ?? ?? 0A D7 A3 3E 66 66 06 40 85 6B 80 3F A0 77").Result;
                
                 MessageBox.Show("adresse aob " + fuel.ToString("x8")+ " " + fuel + " " + min + Environment.NewLine);

**Comment by erfg12** [comment]
Please don't scan the entire length of your computer's memory. Pick a min and max. Is this a 64bit game and if so, did you compile your trainer with x64 target?

**Comment by bozoweed** [comment]
yes it's in x64 because when use pointer it's work and can attach to process but for scan nothing work low and high valu change nothing

**Comment by bozoweed** [comment]
i have just try this 
 long fuel =  m.AoBScan("0x03000000", 0x0400000, "?? ?? ?? ?? 0A D7 A3 3E 66 66 06 40 85 6B 80 3F A0 77").Result;

but steel not work

**Comment by erfg12** [comment]
Are you using the latest version?

**Comment by bozoweed** [comment]
i have juste downoald to night from nuget in visualstudio

**Comment by erfg12** [comment]
ok, talk to me in the Discord chat. GitHub is for bug reports.

**Comment by bozoweed** [comment]
can you send me discord?

**Comment by erfg12** [comment]
You can use the Wiki under the support section for that.

**Comment by bozoweed** [comment]
link broken

**Comment by erfg12** [comment]
refresh page

**Comment by ardonos** [comment]
Hey i mean, thats now a long time ago...
But iam confused, here is no solution. Only a hint to dc. 

So i had the same problem.
I find via CE every time my bytearray. 
But with the latest memory pack from nuget i dont can find a adress by search for my bytearray.  
I find the right process id, but then every time i get no results.

Anyone here who can help, would be very great :)
