### ISSUE TITLE
input string was not in a correct format.

### ISSUE THREAD

**Issue by gaminfish** [erfg12/memory.dll#73]
I'm trying to create a Minecraft Bedrock client and every time I attempt to use the WriteMemory Function it returns an error:
input string was not in a correct format. I've tried using ToString with a float but no matter what I do it doesn't seem to work.
I apologize if this is the wrong place to ask this, but I got no help for this error on the discord server.
`
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Memory;

namespace Octo_Client
{
    public partial class OctoMain : Form
    {
        public Mem m = new Mem();

        public OctoMain()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            int mcPID = m.GetProcIdFromName("Minecraft.Windows");
            bool openProc = false;
            if (mcPID > 0)
            {
                openProc = m.OpenProcess(mcPID);
                Status.Text = "Minecraft Is connected!";
            }
            else
            {
                Status.Text = "Minecraft Is not open!";
            }
        }

        private void Speed_CheckedChanged(object sender, EventArgs e)
        {
            if (Speed.Checked)
            {
                m.WriteMemory("Minecraft.Windows.exe+0x036DD9F8,0x9C,0x1F0,0x18,0x438,0x100,0x580.0x140,0x80", "float", "10");
                Status.Text = "Speed was enabled and was set to" + SpeedValue.Text + "!";
            }else if (Speed.Checked == false){
                m.WriteMemory("Minecraft.Windows.exe+0x036DD9F8,0x9C,0x1F0,0x18,0x438,0x100,0x580.0x140,0x80", "float","1");
                Status.Text = "Speed was disabled!";
            }
        }
    }
}
`

**Comment by ItsZayahh** [comment]
I need help on this too
