### ISSUE TITLE
Trainer can no longer read, write or freeze memory.

### ISSUE THREAD

**Issue by gaminfish** [erfg12/memory.dll#77]
I was working solely on UI design for my trainer after I had the basic functionality I wanted. Then when it came to testing it, all of my functions that used memory.dll wouldn't run. I decided to test by making a label that showed whether I was facing an entity, but that always returned 0. It seems like it is no longer able to use the write memory and read memory functions, as it's still able to get the games PID.

**Comment by ElGrandeKobra** [comment]
Make sure you're running the trainer in admin mode, just go to app.manifest of your project and set requestedExecutionLevel to requireadministrator
![Detail:](https://user-images.githubusercontent.com/55895252/87607579-f48b0b00-c6fd-11ea-8007-1c45dacae513.png)

**Comment by erfg12** [comment]
No response.
