### ISSUE TITLE
Unable to Write Or Read Protected Memory Using AOB

### ISSUE THREAD

**Issue by hammad2224** [erfg12/memory.dll#78]
I am trying to read aob from the memory

IEnumerable<long> AoBScanResults = await MemLib.AoBScan(0x00000000, 0x90000000, "AA 04 00 02 04 02 00 02", false,false);

i get no result.

but when i try to read byte // the address is taken from the cheat engine after finding the above patteren in cheat engine.
var result1=MemLib.ReadByte("0x6133218").ToString("X");         // Return AA from the memory which is correct.
var result2=MemLib.ReadByte("0x6133219").ToString("X");         // Return 4 from the memory which is correct.
var result3=MemLib.ReadByte("0x613321A").ToString("X");         // Return 0 from the memory which is correct.
var result4=MemLib.ReadByte("0x613321B").ToString("X");         // Return 2 from the memory which is correct.
var result5=MemLib.ReadByte("0x613321C").ToString("X");         // Return 4 from the memory which is correct.

its not letting me read the pattern via the AoBScan
and same thing it is not letting me write the memory as well. no exception comes but when i read the value it is unchanged.

Note: I am trying to read protected memory.

**Comment by erfg12** [comment]
Ask in Discord.
