### ISSUE TITLE
AoB scanning partial masking not working

### ISSUE THREAD

**Issue by hammad2224** [erfg12/memory.dll#80]
Ask in our Discord channel first, please. https://discord.gg/ddhGacy

i asked this question in discord 
no one is answering 

AoB scanning with partial masking not working i tried to find this pattern 
? ? ? ? ? ? ? ? AA D0 4D C2 00 A0 A0 E1 DC 04 9F E5 01 80 A0  
and i can find that in cheat engine but unable to find that in memory.dll
although memory.dll can find full pattern easily

**Comment by erfg12** [comment]
Show your code.

**Comment by hammad2224** [comment]
var _mem=new Memory();
var address = _mem.FindPattern("? ? ? ? ? ? ? ? 24 D0 4D E2 00 A0 A0 E1 DC 04 9F E5 01 80 A0");
address = "0x" + address;
_mem.MemLib.ChangeProtection(address, _mem.MemoryProtection.ReadWrite, out oldProtect);
_mem.MemLib.WriteMemory(address, "bytes", "00 00 A0 E3 1E FF 2F E1 24 D0 4D E2 00 A0 A0 E1 DC 04 9F E5 01 80 A0");
_mem.MemLib.ChangeProtection(address, _mem.MemoryProtection.ReadOnly, out oldProtect1);

**Comment by erfg12** [comment]
You have to open the process first.

**Comment by hammad2224** [comment]
offcourse the process needs to open which is done before this code
i just sent this code which is working for other patterns but not for partial Aob scanning
the problem is if i place other patterns then it finds the address fine but the partial address it returns 0

**Comment by hammad2224** [comment]
![Partial Address](https://user-images.githubusercontent.com/10448430/91747882-ea8e7000-ebb6-11ea-985a-17789abb9b08.PNG)

**Comment by erfg12** [comment]
A few questions. Are you using the latest version, and did you check 32/64bit compatibility? With the wild cards it’s possible it’s picking up other addresses and possibly breaking the loop.

**Comment by hammad2224** [comment]
yes i am using the latest version of the code. i did not check 32 bit or 64 bit compatibility. but as i mentioned that Memory.dll is finding patterns already fine. so i think it is compatible. only partial patterns it fails.
i dont know i have taken the code from your github and placed it inside the project and now looking into debuggin it line by line that what is different when normal pattern is called and it finds the address and when partial pattern is called.

i think its something to do with masking of the partial address but not sure. will let you know if i find something 
thanks for the help

**Comment by erfg12** [comment]
Download the Memory.dll source, add the dll, remove any try/catch statements. See if it crashes with an error message.

**Comment by hammad2224** [comment]
yahh that is a good advice.
i will try that probably.
will update you as soon as i do it 

thanks 
regards,
Hammad

**Comment by hollow87** [comment]
`FindPattern` should be a private method use `AoBScan` instead
Also try using ?? instead of ? as the code supports partial matching of a byte and I want to make sure that the partial match is not the issue here.

**Comment by hammad2224** [comment]
that was the first thing i did replaced ? with ?? but same results.
i tried removing the try catch it simply does not go in try catch as no exception comes.
it simply can not find it 
very strange.

**Comment by hollow87** [comment]
Apologies for the lack of activity regarding this issue.
Can you confirm if this bug still exists?

Also please verify you are setting the `readable` parameter on the `AoBScan` method to `true`, the `writable` parameter to `false` and the `executable` parameter to `false`; as it appears from the code you provided, your intent is to read, read only memory.

**Comment by erfg12** [comment]
No reply, closing the issue. Please re-open if you need help.
