### ISSUE TITLE
Mem.MemoryProtection

### ISSUE THREAD

**Issue by vlacre** [erfg12/memory.dll#81]
I get an error when I want to change the protection of the address "The type name "ExecuteRead" does not exist in the type "Mem.MemoryProtection"."

**Comment by erfg12** [comment]
Please provide some code.

**Comment by vlacre** [comment]
Address Protection is: Execute/ReadOnly, I want to change it to Execute/ReadWrite, but Visual Studio shows an error "The type name "ExecuteRead" does not exist in the type "Mem.MemoryProtection", if I change "out Mem.MemoryProtection.ExecuteRead" to any other value (e.g., Mem.MemoryProtection.ReadOnly), it will give the same error
`                NumPad3 = !NumPad3;
                if (NumPad3 && isNoReloadActive == false)
                {
                    memLib.ChangeProtection("BF2142.exe+0x00685228,0x6C,0x80,0x4,0x1E8,0x1C4,0x8,0x0", Mem.MemoryProtection.ExecuteReadWrite, out Mem.MemoryProtection.ExecuteRead protection);
                    memLib.FreezeValue("BF2142.exe+0x00685228,0x6C,0x80,0x4,0x1E8,0x1C4,0x8,0x0", "int", "200");
                    isNoReloadActive = true;
                    soundActivated.Play();
                    labelNumPad3.ForeColor = Color.Red;
                    labelNumPad3NoReload.ForeColor = Color.Red;
                }`

**Comment by Sadulisten** [comment]
``
NumPad3 = !NumPad3; 

if (NumPad3 && isNoReloadActive == false) { 
	memLib.ChangeProtection("BF2142.exe+0x00685228,0x6C,0x80,0x4,0x1E8,0x1C4,0x8,0x0", 
							Mem.MemoryProtection.ExecuteReadWrite, // The protection you want to set
							out Mem.MemoryProtection protection); // This gives you the original protection said on the address
																			  // So, the type should be 'Mem.MemoryProtection' or 'var'
	memLib.FreezeValue("BF2142.exe+0x00685228,0x6C,0x80,0x4,0x1E8,0x1C4,0x8,0x0", "int", "200");
	isNoReloadActive = true; 
	soundActivated.Play(); 
	labelNumPad3.ForeColor = Color.Red; 
	labelNumPad3NoReload.ForeColor = Color.Red; 
}
``

Compare this code with yours.

**Comment by vlacre** [comment]
Thanks, now it works :)
