### ISSUE TITLE
Modules missing?

### ISSUE THREAD

**Issue by erfg12** [erfg12/memory.dll#83]
Someone reported that "server.dll" does not show up in the module list.
Another user reported "UnityPlayer.dll" does not show in the module list either.

Some investigation may be needed.

**Comment by kevinjpetersen** [comment]
Not sure if this is related, but I had an issue similar to this.

I was working with a 32-bit game, and when I tried to use Memory.dll with a given Module, it couldn't find it.
I then figured out that the games architecture (32/64-bit) you're targeting, has to match with the Trainer/Program you're developing. So you'll have to compile the Trainer/Program for 32-bit if the process/game you're targeting is running 32-bit (and vice versa)

**Comment by erfg12** [comment]
Here's how Cheat Engine finds the modules in .NET applications: https://github.com/cheat-engine/cheat-engine/blob/3e53faa531008b2ef735efcd9a8f0d3e5c3c7623/Cheat%20Engine/MonoDataCollector/MonoDataCollector/PipeServer.cpp#L220

**Comment by erfg12** [comment]
Windows needs to have the trainer match the program to list the modules correctly. If your game is x86, you need to build an x86 trainer. If your game is x64, you need to build an x64 trainer. If you compile your trainer as "Any CPU" you need to uncheck the "Prefer 32bit" checkbox in Project Settings > Build.
