### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by ProfessorQu** [erfg12/memory.dll#87]
The OpenProcess function gives a System.IO.FileNotFoundException.
I don't know why it does this because the first thing I do is:
```
int PID = meme.GetProcIdFromName("ac_client");
            if (PID > 0)
            {
                meme.OpenProcess(PID);
            }
```

I really don't know what I did wrong.

**Comment by erfg12** [comment]
You're talking about,

```CSharp
System.BadImageFormatException: 'Could not load file or assembly 'Memory, Version=1.2.20.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'
```

This means you did not un-check the Prefer 32bit checkbox on the `Project Properties > Build` page.

Otherwise, you're missing the `System.Security.Principal.Windows` NuGet package.
