### ISSUE TITLE
Memory write failure in some emulators

### ISSUE THREAD

**Issue by Urahara3000** [erfg12/memory.dll#88]
I did a test today in the PPSSPP emulator through a trainer, and whenever I use any function of the Trainer, the emulator freezes and closes and in the Cheat Engine the codes stay with ??, the same process also occurs in the Dolphin emulator, this error did not happen in version 1.2.19 of the Dll, I think it is something related to memory protection, Dark Byte had this problem on the Cheat Engine before and it has already fixed this problem in a recent version of CE, see the image below:

https://i.imgur.com/1f3QiyS.png

please correct this problem in the next version of the Dll, thank you in advance.

**Comment by erfg12** [comment]
https://github.com/cheat-engine/cheat-engine/blob/d598f79bb36642c6df48b5c7f05fd0236a320b62/Cheat%20Engine/dbk32/DBK32functions.pas#L2059

**Comment by Urahara3000** [comment]
> https://github.com/cheat-engine/cheat-engine/blob/d598f79bb36642c6df48b5c7f05fd0236a320b62/Cheat%20Engine/dbk32/DBK32functions.pas#L2059
> 
> https://github.com/erfg12/memory.dll/blob/master/Memory/memory.cs#L686
> 
> https://github.com/erfg12/memory.dll/blob/master/Memory/memory.cs#L1122
> 
> We try to change protection before the write, is this what's causing it to crash? Try compiling memory.dll and removing that line in WriteMemory.

**Comment by Urahara3000** [comment]
I removed the lines that you showed me in the images, I just did a new test here in the PPSSPP emulator, and everything worked normal, now it should work in the other emulators too, the problem must be something in those lines that I removed, I can't say exactly what it is because I don't have knowledge in this part of writing and reading memory, anyway, thank you very much for the answer.

**Comment by erfg12** [comment]
added https://github.com/erfg12/memory.dll/commit/0bddf5c415e28633210ae7c72599f6cb85d71fea
