### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by debil9877654321** [erfg12/memory.dll#9]
My code was working well with memory.dll, then I tested it after 3 days and it throw error
It happens when I try to write into process
`System.NullReferenceException: Object reference not set to an instance of object.
   v Memory.Mem.get64bitCode(String name, String path, Int32 size)
   v Memory.Mem.getCode(String name, String path, Int32 size)
   v Memory.Mem.writeMemory(String code, String type, String write, String file)
   v Cli3nt_Mars.Form1.checkBox1_CheckedChanged(Object sender, EventArgs e)
   v System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   v System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   v System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   v System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ButtonBase.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`
I'm pretty sure my code is 100% correct! It worked for other people, but for me it just stopped working and process where I'm writing is running.. So I think It's caused by my windows, so what should I do to make it working again?

**Comment by erfg12** [comment]
Something tells me your address is now incorrect. Can you confirm the address works currently in Cheat Engine?
