### ISSUE TITLE
System.NullReferenceException (on m.writememory)

### ISSUE THREAD

**Issue by Woomeli** [erfg12/memory.dll#93]
when i start program it gives System.NullReferenceException
code :
      
if (checkBox1.Checked)
   m.WriteMemory("base+0x383B76", "bytes", "0x8B 0x44 0xC2 0x10");
else
   m.WriteMemory("base+0x383B76", "bytes", "0x8B 0x44 0xC2 0x20");

what i do wrong? :D

**Comment by GEONEXX** [comment]
Did you find solution for this? I have same problem right now.

**Comment by osadrac** [comment]
> Did you find solution for this? I have same problem right now.

show your problem, its function, we can't help without information

**Comment by GEONEXX** [comment]
if (checkBox1.Checked == true)
m.WriteMemory("base+CAC9E0", "bytes", "90 90");
else
m.WriteMemory("base+CAC9E0", "bytes", "4F 6E");

This is my problem.

**Comment by GEONEXX** [comment]
if (checkBox1.Checked == true) 

m.WriteMemory("base+CAC9E0", "bytes", "90 90"); 

else 

m.WriteMemory("base+CAC9E0", "bytes", "4F 6E");

This is my problem.

**Comment by osadrac** [comment]
> if (checkBox1.Checked == true)
> m.WriteMemory("base+CAC9E0", "bytes", "90 90");
> else
> m.WriteMemory("base+CAC9E0", "bytes", "4F 6E");
> 
> This is my problem.

there is still little information, but believing that the offset is correct you need to pass them to hexadecimal, (0x90 0x90), the offset of the base address as well (0xCAC90E),

Example:
m.WriteMemory("base+0xCAC9E0", "bytes", "0x4F 0x6E");

**Comment by GEONEXX** [comment]
Yes i did do that m.OpenProcess("GAME_NAME").

**Comment by GEONEXX** [comment]
I try to do that aswell m.WriteMemory("base+0xCAC9E0", "bytes", "0x4F 0x6E");

**Comment by osadrac** [comment]
> Yes i did do that m.OpenProcess("GAME_NAME").

Did you check if you got the correct base?

**Comment by GEONEXX** [comment]
Yes

**Comment by osadrac** [comment]
testing this write there is no problem, it is probably something related to the address obtained by the offset or the base of the process

**Comment by GEONEXX** [comment]
Now it doesn't detect my game

**Comment by osadrac** [comment]
check if you are passing the process name correctly and opening visual studio and the game as administrator

**Comment by GEONEXX** [comment]
Alr i try

**Comment by GEONEXX** [comment]
Still doesn't detect

**Comment by osadrac** [comment]
what process name are you going through?

**Comment by GEONEXX** [comment]
Im doing  cheats for growtopia. And in task manager process name is Growtopia

**Comment by osadrac** [comment]
Growtopia is the name of the executable or the name of the window? there is a difference between the two. check if the executable is Growtopia.exe

**Comment by GEONEXX** [comment]
I tried Growtopia.exe too but it didn't work.  Name of the window is Growtopia and executable is Growtopia.exe
