### ISSUE TITLE
WriteMove Slow

### ISSUE THREAD

**Issue by hollow87** [erfg12/memory.dll#94]
The Thread sleep should be removed from WriteMove https://github.com/erfg12/memory.dll/blob/84dbcb9a52a5845cdfd3b00774bc0d9d77f85bac/Memory/memory.cs#L1195

**Comment by snuckdev** [comment]
Yeah, of course.

**Comment by ragnaroks** [comment]
may instead of `SpinWait.SpinUntil(()=>false,ms)`

**Comment by erfg12** [comment]
Fixed in https://github.com/erfg12/memory.dll/commit/f4af8514d0b7a04b4e19ecfb6a02cb02ec1d9525
