### ISSUE TITLE
Error when trying to test and debug a program using memory.dll

### ISSUE THREAD

**Issue by EpicNation** [erfg12/memory.dll#95]
The error:

System.InvalidOperationException: 'An error occurred creating the form. See Exception.InnerException for details.  The error is: Could not load file or assembly 'Memory, Version=1.2.21.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'

**Comment by RedDot-3ND7355** [comment]
Missing the dll.
Enable "copy to local" for the reference.
