### ISSUE TITLE
CodeCave x64 Cause System.OverflowException

### ISSUE THREAD

**Issue by speedinfected** [erfg12/memory.dll#97]
Ask in our Discord channel first, please. https://discord.gg/ddhGacy
I ask on Discord and the solution would be to change the code from the line:
https://github.com/erfg12/memory.dll/blob/883ad2be90ee67cd915aa841fd04b390c909cb76/Memory/memory.cs#L1646
However, I have no knowledge of the programming language. I would like, if possible, to have it fixed so that we can better use this amazing tool.
I did a last test of the CreateCodeCave function today. This was the fifth game in 64 bits. In the 5 games the return is the same: System.OverflowException.
All addresses are correct and verified. The problem is only in the CreateCodeCave function. The other functions work perfectly! Thanks for your attention, nice job again!

**Comment by ArmYof0n3** [comment]
Hi !
for CodeCave to work properly, I think FindFreeBlockForRegion needs to change this way 👍 

```
            do
            {
                if (VirtualQueryEx(pHandle, current, out mbi).ToUInt64() != 0)
                {
                    ......
                }
                      
            } while ((long)current > (long)maxAddress || (long)previous > (long)current);
              return ret;
```

**Comment by speedinfected** [comment]
Help from a dear friend, problem solved!
