### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by derluc4** [erfg12/memory.dll#98]
When I try to compile the code I get this error message: System.BadImageFormatException: Could not load file or assembly '"Memory, Version=1.2.21.0, Culture=neutral, PublicKeyToken=null"  or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by erfg12** [comment]
It seems that you are using the 64-bit version of the tool to install a 32-bit/x86 architecture application.
