### ISSUE TITLE
Module was not found in module list!

### ISSUE THREAD

**Issue by GameplayGoon** [erfg12/memory.dll#99]
Hi

Im having issues with Halo MCC. The game has several game engines inside one process and uses modules for each game, when enabling a feature in my trainer heres an example of what worked....

```
Private Sub CheckBox9_CheckedChanged(sender As Object, e As EventArgs) Handles CheckBox9.CheckedChanged
        m.OpenProcess(ComboBox1.Text)
        If CheckBox9.Checked = True Then
            m.WriteMemory("halo1.dll+BE9F4E", "bytes", "90 90 90 90 90 90")
        End If
        If CheckBox9.Checked = False Then
            m.WriteMemory("halo1.dll+BE9F4E", "bytes", "66 47 89 44 8E 08")
        End If
        m.CloseProcess()
    End Sub
```

You can see opening and closing the game process each time I write to memory worked fine and it successfully found the halo1.dll module or whatever game module I was playing inside Halo MCC. However someone told me it was better and cleaner to just open the process once when the game process is found, using this method though only works if you load your program after you have loaded into the game, it will find the module without problem.

But if you load into another game inside Halo MCC for example Halo 2 which uses halo2.dll module, it will not be found unless you restart your application or use the m.OpenProcess command each time you write to memory. Using the m.GetModules() command won't work either as it fails to find the new game module that has been loaded.

`Module halo2.dll was not found in module list!`

I reported this in Discord but was asked to file a report here as it could be a bug. If you need anymore info let me know.

Edit: Update user "Ohm" provided me with this temporary fix that solved the problem

```
Public Sub UpdateModules(ByVal memoryDllInstance As Mem)
    If memoryDllInstance Is Nothing Then Return
    If memoryDllInstance.theProc Is Nothing Then Return
    memoryDllInstance.theProc.Refresh()
    memoryDllInstance.modules.Clear()

    For Each [Module] As ProcessModule In memoryDllInstance.theProc.Modules
        If Not String.IsNullOrEmpty([Module].ModuleName) AndAlso Not modules.ContainsKey([Module].ModuleName) Then memoryDllInstance.modules.Add([Module].ModuleName, [Module].BaseAddress)
    Next

    Debug.WriteLine("Found " & modules.Count() & " process modules.")
End Sub
```

Thanks

**Comment by erfg12** [comment]
More information needed.

1) Is your game and your trainer matching types? (32bit vs 64bit). They must match.
2) Does your trainer have elevated privileges.

Also:
The module list is updated every time you open the process. So, if you have to swap processes, then do so by opening the other process. Memory.dll is only programmed to focus on 1 application at a time. But swapping, changing or cycling through processes is fine.

**Comment by GameplayGoon** [comment]
Yes they match and Im running my tool as admin.

The modules are in one process the process isn't being changed, the memory.dll is just finding to find the games module...
